name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - revanced-extended
  pull_request:
    branches:
      - revanced-extended

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the release step uses its own credentials:
          # https://github.com/cycjimmy/semantic-release-action#private-packages
          persist-credentials: false
          fetch-depth: 0

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Build with Gradle
        run: ./gradlew generateMeta clean

      - name: Setup semantic-release
        run: npm install

      - name: Release
        run: npm exec semantic-release
